

task:
  name: build_ios
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  osx_instance:
    image: high-sierra-xcode-9.4.1
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    ENGINE_PATH: "/tmp/engine"
    DEPOT_TOOLS: "/tmp/depot_tools"
    PATH: "$DEPOT_TOOLS:$PATH"
    DEPLOY_TOKEN: ENCRYPTED[5359c00cb515791954226adbc909f69ad81739962c81c175ce79323a6db20291b3dd7476178704e12355b660668c2b8d]
  depot_tools_script:
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git $DEPOT_TOOLS
  gclient_sync_script: |
    mkdir -p $ENGINE_PATH/src
    echo 'solutions = [{"managed": False,"name": "src/flutter","url": "https://github.com/FlutterPrograms/EngineDynamic.git","deps_file": "DEPS", "custom_vars": {"download_android_deps" : False, "download_windows_deps" : False,},},]' > $ENGINE_PATH/.gclient
    cd $ENGINE_PATH/src
    rm -rf flutter
    rm -rf out && rm -rf target
    # mv $CIRRUS_WORKING_DIR flutter
    gclient sync -v
  checkout_source_script: |
    cd $ENGINE_PATH/src/flutter
    git remote -v
    git fetch origin --prune
    git show -s
    echo $CIRRUS_BRANCH && git checkout $CIRRUS_BRANCH
    git show -s
  gclient_sync_again_script: |
    cd $ENGINE_PATH/src
    gclient sync
  compile_ios_debug_script: |
    cd $ENGINE_PATH/src
    mkdir -p target/ios_debug
    ./flutter/tools/gn --ios
    ninja -C out/ios_debug
    cp -Rf out/ios_debug/Flutter.framework target/ios_debug/Flutter.framework
    rm -rf out/ios_debug
  compile_ios_debug_sim_script: |
    cd $ENGINE_PATH/src
    mkdir -p target/ios_debug_sim
    ./flutter/tools/gn --ios --simulator
    ninja -C out/ios_debug_sim
    cp -Rf out/ios_debug_sim/Flutter.framework target/ios_debug_sim/Flutter.framework
    rm -rf out/ios_debug_sim
  lipo_framework_script: |
    cd $ENGINE_PATH/src
    mkdir -p target/ios_debug_all
    cp -Rf target/ios_debug/Flutter.framework target/ios_debug_all/Flutter.framework
    lipo -create target/ios_debug/Flutter.framework/Flutter target/ios_debug_sim/Flutter.framework/Flutter -output target/ios_debug_all/Flutter.framework/Flutter
    lipo -info target/ios_debug_all/Flutter.framework/Flutter
  deploy_framework_script: |
    ./hot_update_ci/deploy_framework.sh
